package com.oocpa.processnewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "OocApplication")
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "APPLICATION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	private long id;

	@javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.EAGER, cascade = {
			javax.persistence.CascadeType.PERSIST,
			javax.persistence.CascadeType.MERGE,
			javax.persistence.CascadeType.REMOVE,
			javax.persistence.CascadeType.REFRESH})
	private com.oocpa.processnewapplication.Patient patient;

	@javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.EAGER, cascade = {
			javax.persistence.CascadeType.PERSIST,
			javax.persistence.CascadeType.MERGE,
			javax.persistence.CascadeType.REMOVE,
			javax.persistence.CascadeType.REFRESH})
	private com.oocpa.processnewapplication.Provider provider;

	public Application() {
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public com.oocpa.processnewapplication.Patient getPatient() {
		return this.patient;
	}

	public void setPatient(com.oocpa.processnewapplication.Patient patient) {
		this.patient = patient;
	}

	public com.oocpa.processnewapplication.Provider getProvider() {
		return this.provider;
	}

	public void setProvider(com.oocpa.processnewapplication.Provider provider) {
		this.provider = provider;
	}

	public Application(long id,
			com.oocpa.processnewapplication.Patient patient,
			com.oocpa.processnewapplication.Provider provider) {
		this.id = id;
		this.patient = patient;
		this.provider = provider;
	}

}