package com.oocpa.processnewapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "OocPatient")
public class Patient
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PATIENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	private java.lang.Long id;

	private java.lang.Long healthNum;

	private java.lang.String firstName;

	private java.lang.String lastName;

	public Patient() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getHealthNum() {
		return this.healthNum;
	}

	public void setHealthNum(java.lang.Long healthNum) {
		this.healthNum = healthNum;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public Patient(java.lang.Long id, java.lang.Long healthNum,
			java.lang.String firstName, java.lang.String lastName) {
		this.id = id;
		this.healthNum = healthNum;
		this.firstName = firstName;
		this.lastName = lastName;
	}

}